### ISSUE TITLE
Ordnerstruktur wird nicht korrekt angelegt.

### ISSUE THREAD

**Issue by G4Cab** [ThorstenPferdekaemper/FHEM-FUIP#11]
bei einer frischen Installation via `update all fuip` wird unter /opt/FHEM/lib/FUIP/ der Ordner js nicht angelegt, nachdem dieser manuell angelegt wurde lässt sich fuip installieren.

**Comment by ThorstenPferdekaemper** [comment]
Hi,
ich habe das grad mal ausprobiert, also eine komplett frische FHEM-Installation, dann update add... und update all... für FUIP und FTUI. Hat alles geklappt. D.h. ich konnte das Problem nicht nachvollziehen. Außerdem hat niemand sonst im Forum das Problem "gemeldet". 
Gestern gab es allerdings ein paar Minuten, in denen das Git-Repo nicht ganz konsistent war. Möglicherweise hat es dadurch seltsame Effekte gegeben.
Willst Du das nochmal probieren? Sollte es tatsächlich nachvollziehbar sein, dann können wir nochmal forschen.
Gruß,
    Thorsten

**Comment by ThorstenPferdekaemper** [comment]
...Issue geschlossen, da es nicht nachvollziehbar ist,
