### ISSUE TITLE
FUIP::View::Title - TextBox steht über Box raus

### ISSUE THREAD

**Issue by greewoo** [ThorstenPferdekaemper/FHEM-FUIP#35]
Die TextBox von FUIP::View::Title steht über die eigentliche Box raus auch bei kurze Titeln, das führt bei Smartphone-Ansichten dazu, dass das Scrollen nach rechts möglich ist, obwohl alles auf die Breite passen würden
<img width="581" alt="bildschirmfoto 2018-10-28 um 10 54 26" src="https://user-images.githubusercontent.com/35729793/47614449-49a56a00-daa0-11e8-8b44-988f4f042b86.png">

**Comment by ThorstenPferdekaemper** [comment]
Hi,
ich habe mir das mal angeschaut und auch ein bisschen rumprobiert. Allerdings habe ich bisher noch keine wirklich gute Lösung gefunden. ...ich bleibe aber dran.
Gruß,
     Thorsten

**Comment by ThorstenPferdekaemper** [comment]
Schau mal hier:
https://forum.fhem.de/index.php/topic,92768.0.html

Allerdings müssen jetzt noch WeatherDetail und WeatherOverview angepasst werden.

**Comment by ThorstenPferdekaemper** [comment]
Weather Views sind jetzt auch angepasst.
