### ISSUE TITLE
View für Images mit Autorefresh basierend auf dem HTML-View

### ISSUE THREAD

**Issue by hawkeyexp** [ThorstenPferdekaemper/FHEM-FUIP#38]
Hi,

ich habe vor einiger Zeit Fuip für ein kleines Kiosk auf RPI-Basis eingesetzt was gut klappt allerdings musste ich erst mal etwas suchen wie ich einen Autorefresh für Images einbaue (Aktualisierung meiner Karte vom Staubsauger-Robby)

Ich denke viele werden da auch erst mal suchen daher hier mal ein gut funktionierendes Template was man vielleicht ein fertiges View-Template überführen könnte (funktioniert so direkt im HTML-View):

```
<script language="javascript" type="text/javascript" >
<!--
function ChangeMedia(){
	var d = new Date();
	var t = d.getTime();
	document.getElementById('map').src = "/fhem/www/livemap/map.png?"+t;
}
var reloadcam = setInterval("ChangeMedia()",5000);
-->
</script>

<img src="/fhem/www/livemap/map.png" alt="Karte" width="400" height="240" id="map">
```

Parameter fürs Template würde ich folgendes Vorschlagen:

Name, Dateipfad, Image-ID, Refreshinterval, Höhe, Breite optional vielleicht noch Popup auf Original-Größe

**Comment by ThorstenPferdekaemper** [comment]
Hi,
wenn Du das ins FHEM-Forum schreibst, dann erreicht das vielleicht auch jemanden. Hier liest glaube ich kaum jemand mit.
Gruß,
   Thorsten

**Comment by hawkeyexp** [comment]
Dachte halt ich adressiere den Vorschlag direkt an den Entwickler :-)

**Comment by ThorstenPferdekaemper** [comment]
Das ist ja auch gut und eigentlich richtig. Allerdings habe ich momentan nicht so viel Zeit. Da ist es sinnvoller, so etwas im Forum zu zeigen, damit es vielleicht andere benutzen können.

**Comment by hawkeyexp** [comment]
ich mach mal zu - Template hatte ich im Forum mal hochgeladen.
