### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by prnzngr** [ThorstenPferdekaemper/FHEM-FUIP#39]
Hello,
FUIP is not working because of:
`Attempt to reload lib/FUIP/Model.pm aborted.
Compilation failed in require at ./FHEM/42_FUIP.pm line 43.
BEGIN failed--compilation aborted at ./FHEM/42_FUIP.pm line 43.`
Can you please check

**Comment by ThorstenPferdekaemper** [comment]
Hi,
could you give me a bit more context? E.g. there should be some more detailed message regarding what's wrong with Model.pm.
In addition: Can we handle this in the FHEM Forum?
Regards,
   Thorsten

**Comment by prnzngr** [comment]
I had to delete FUIP and define it again. now its working
